FROM debian:stretch

RUN apt-get update && \
    apt-get install -y wget openjdk-8-jdk openjdk-8-jre

RUN mkdir /opt/hadoop && \
    wget -q -O- http://mirrors.estointernet.in/apache/hadoop/common/hadoop-2.8.5/hadoop-2.8.5.tar.gz \
    | tar -xzv -C /opt/hadoop --strip 1

RUN apt-get install -y supervisor telnet net-tools gettext

RUN wget -q -O- http://mirrors.estointernet.in/apache/pig/pig-0.17.0/pig-0.17.0.tar.gz \
    | tar -xzv -C /opt 

ENV HADOOP_HOME=/opt/hadoop \
    JAVA_HOME=/usr \
    HDFS_PORT=9000

WORKDIR /opt/hadoop
