FROM ubuntu:disco

RUN apt-get update && \
    apt-get install -y wget openjdk-8-jdk openjdk-8-jre

RUN mkdir /opt/spark && wget -q -O- http://mirrors.estointernet.in/apache/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz \
    | tar -xzv -C /opt/spark --strip 1

RUN apt-get install -y supervisor telnet net-tools gettext python-pip python-dev

RUN useradd -ms /bin/bash spark

RUN chown spark:spark /opt/spark -R

RUN apt-get install -y vim

USER spark
WORKDIR /home/spark

COPY requirements-spark.txt requirements.txt
RUN pip install --user -r requirements.txt

ENV SPAKR_HOME=/opt/spark \
    PATH=/opt/spark/bin:/home/spark/.local/bin:$PATH \
    HADOOP_CONF_DIR=/opt/spark/hadoop-conf
