FROM ubuntu:19.04

RUN apt-get update && \
    apt-get install -y wget openjdk-8-jdk openjdk-8-jre

RUN mkdir /opt/drill && wget -q -O- http://mirrors.estointernet.in/apache/drill/drill-1.15.0/apache-drill-1.15.0.tar.gz \
    | tar -xzv -C /opt/drill --strip 1

RUN useradd -ms /bin/bash drill

RUN chown drill:drill /opt/drill -R
USER drill
WORKDIR /home/drill

ENV SPAKR_HOME=/opt/drill \
    PATH=/opt/drill/bin:/home/drill/.local/bin:$PATH
