FROM ubuntu:19.04

RUN apt-get update && \
    apt-get install -y wget openjdk-8-jdk openjdk-8-jre

RUN mkdir /opt/drill && wget -q -O- http://mirrors.estointernet.in/apache/drill/drill-1.15.0/apache-drill-1.15.0.tar.gz \
    | tar -xzv -C /opt/drill --strip 1

RUN useradd -ms /bin/bash drill

RUN apt-get install -y telnet net-tools gettext sudo

RUN chown drill:drill /opt/drill -R && \
    echo "drill ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY conf/drill-on-yarn.conf /home/drill/

ENV DRILL_HOME=/opt/drill \
    PATH=/opt/drill/bin:/home/drill/.local/bin:$PATH \
    HADOOP_CONF_DIR=/opt/drill/hadoop-conf \
    HDFS_URL=hdfs://namenode:9000/

RUN envsubst < /home/drill/drill-on-yarn.conf > /opt/drill/conf/drill-on-yarn.conf && \
    chown drill:drill /opt/drill/conf/drill-on-yarn.conf

USER drill

WORKDIR /home/drill

